apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsq.nsqlookupd.fullname" . }}
  labels:
    {{- include "nsq.commonLabels" . | nindent 4 }}
spec:
  type: {{ .Values.nsqlookupd.service.type }}
  ports:
  - name: http
    port: 4160
    protocol: TCP
    targetPort: http
  - name: tcp
    port: 4161
    protocol: TCP
    targetPort: tcp
  selector:
    {{- include "nsq.nsqlookupd.selectorLabels" . | nindent 4 }}
